name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 20 * * 6
  workflow_dispatch:

env:
  packages_to_install: shellcheck

jobs:
  shellcheck:
    name: shellcheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install supplementals
        shell: bash
        run: |
          sudo apt update
          sudo apt install --no-install-recommends ${{ env.packages_to_install }}

      - name: Lint
        shell: bash
        run: make -k -j lint
